/*COSAS PENDIENTES AAAAAAAAAAAAAAAAAAAAAA
 * 
 * - CAMBIAR EL CIRTCUITO Y MEJORAR EL DISEÑO DEL MINIJUEGO DE ENTRENAMIENTO DE OBSTACULOS
 * - AGREGARLE AL MINIJUEGO DE REMATE QUE LA IA GUARDE LA POSICION DEL ULTIMO CARRIL AL QUE LE LANZO LA PELOTA PARA QUE NO SE REPITA
 * - AGREGARLE AL MINIJUEGO DE VOLLEY SAQUE POR CADA RONDA DEPENDIENDO DE QUIEN FUE EL ULTIMO PUNTO Y LA REGLA DE TOQUES
 * - AGREGARLE AL MINIJUEGO DE VOLLEY UNA FEATURE AL JUGADOR COMO LA INTERFAZ PARA REMATAR O PASAR BALON
 * - HAY UN BUG EN EL DE VOLLEY Q PODI GANAR PEGANDOLE HACIA ARRIBA A LA BOLA ARREGLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAR
 * - CONDICIONES QUE SI PIERDE LO MANDE A LINEAS ALTERNATIVAS
 * - IMPLEMENTAR SPRITES Y ANIMACIONES A LOS MINIJUEGOS 
 */
